# --- Structural Variants ---

[Inversions]
file = 4b5_inversions.bedpe
title = Structural Variants
type = links
color = orange
compact_arcs_level = 2
use_summit = true
height = 2
line_width = 2

[Deletions]
file = 4b5_deletions.bedpe
# Title is intentionally blank here so it doesn't double-print over the Deletions title
title = 
type = links
color = black
line_style = dashed
compact_arcs_level = 2
use_summit = true
overlay_previous = yes
line_width = 2



[Rearangements]
file = 4b5_rearangements.bedpe
# Title is intentionally blank here so it doesn't double-print over the Deletions title
title = 
type = links
color = green
compact_arcs_level = 2
use_summit = true
overlay_previous = yes
line_width = 2

[TS]
file = 4b5_TS.bedpe
# Title is intentionally blank here so it doesn't double-print over the Deletions title
title = 
type = links
color = #00B0F0
compact_arcs_level = 2
use_summit = true
overlay_previous = yes
line_width = 2

# --- Coverage ---

[Coverage]
file = 4b5_coverage_100.bw
title = Read Coverage
color = #333333
min_value = 0
max_value = 7.5
height = 3
type = fill

# --- X-Axis ---

[x-axis]
fontsize = 12
